version: "4.2"

services:
  app:
    container_name: sl-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/home/app
    ports:
      - "8000:8000"
    env_file:
      - .env

networks:
  default:
    driver: bridge

volumes:
  app: